### ISSUE TITLE
Create a new structure for Poster/Flyer/Programme etc

### ISSUE THREAD

**Issue by phgeller** [newtheatre/history-project#10]
something like:

Production Photos:

Publicity Materials:

**Comment by wjdp** [comment]
I think what we'll do is rename `images:` to `photos:` to make that a little clearer. `assets:` goes to `materials:`, but call it Publicity Materials on the page.

For file locations, images will go into the `images/` folder and non-images (binary files) will go in assets `assets/`.

```yaml
photos:
  - title:
    image: show_photo_1.jpg
    caption: "xyz"
materials:
  - type: poster
    image: show_poster.jpg
  - type: flyer
    image: show_flyer.jpg
  - type: programme 
    file: show_programme.pdf     ## Note because this is a file, not an image we use file here. This tells it to look in the assets folder.
```

Oh and we should make a rule to use `.jpg` over `.jpeg`, and to change any to the former.
