### ISSUE TITLE
[/collect/show/] The Made Up Show

### ISSUE THREAD

**Issue by ntbot** [newtheatre/history-project#166]
End user submitted issue from page: [/collect/show/](http://alpha.history.newtheatre.org.uk/collect/show/)
---

# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | The Made Up Show
Playwright | by Fred
Date Start | 01 / 01 / 1980
Date End | 02 / 01 / 1980
Type | Made up show
Venue | New Theatre Studio C

## Synopsis

This show is made up

## Cast

No-one - Everyone
Fred - The cat

## Crew

Director - Alice
Producer - Mark

## Anything Else

Nope

## Submitter

Field | Data
----- | ----
Name | Joe Bloggs
Graduated | 2004

## Attempted File Generation

```
---
title: The Made Up Show
playwright: by Fred
season: ??? (Made up show)
season_sort: ??
period: ??
venue:
  - New Theatre Studio C
date_start: 1980-01-01
date_end: 1980-01-02

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from Joe Bloggs (2004)
published: true
---

This show is made up
```

**
