### ISSUE TITLE
[/collect/show/] Test 2

### ISSUE THREAD

**Issue by ntbot** [newtheatre/history-project#168]
End user submitted issue from page: [/collect/show/](http://alpha.history.newtheatre.org.uk/collect/show/)
---

# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | Test 2
Playwright | 
Date Start |  /  / 
Date End |  /  / 
Type | Test
Venue | ?

## Anything Else

Test with live site

## Submitter

Field | Data
----- | ----
Name | Will Pimblett
Graduated | 2014

## Attempted File Generation

```
---
title: Test 2
playwright: 
season: ??? (Test)
season_sort: ??
period: ??
venue:
  - ?
date_start: --
date_end: --

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from Will Pimblett (2014)
published: true
---


```

**
