### ISSUE TITLE
Seneca's Oedipus

### ISSUE THREAD

**Issue by ntbot** [newtheatre/history-project#1826]
End user submitted issue from page: [/collect/show/](https://history.newtheatre.org.uk/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | Seneca's Oedipus
Playwright | adapted by Ted Huges
Date Start | 17 / 03 / 2006
Date End | 8 / 6 / 2006
Type | Not sure
Venue | New Theatre

## Crew

Technical Costume Designer/Seamstress - Ashley E. Thomas

## Submitter

Field | Data
----- | ----
Name | Ashley E. Thomas
Graduated | 2006

## Attempted File Generation

```
---
title: Seneca's Oedipus
playwright: adapted by Ted Huges
season: ??? (Not sure)
season_sort: ??
period: ??
venue:
  - New Theatre
date_start: 2006-03-17
date_end: 2006-6-8

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from Ashley E. Thomas (2006)
published: true
---


```
**
