### ISSUE TITLE
Handle devised pieces better, syntax changes

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#285]
![image](https://cloud.githubusercontent.com/assets/1690934/10615444/c697a898-7757-11e5-87ce-a2184c0acd23.png)

![image](https://cloud.githubusercontent.com/assets/1690934/10615447/cc17884c-7757-11e5-887a-c5f5745974ae.png)

Currently looks rather awkward. Syntax needs updating. Two options I can see:

## 1

Piggybacking on the playwright attribute.

```yaml
---
title: Little Red
playwright: devised
```

Outputs 'Devised', omits 'by'. Cannot handle who helped devise.

## 2

Bit more flexible, but requires adding a new attribute.

```yaml
---
title: Little Red
devised: true
playwright: cast and crew
```

Outputs 'Devised by cast and crew'

```yaml
---
title: Little Red
devised: true
```

Outputs 'Devised'

*(Note to self, do this with a method in `shows.rb`, then just use show.playwright_formatted or something)*

**Comment by wjdp** [comment]
@newtheatre/editors any thoughts, better ideas?

**Comment by nhyty** [comment]
I prefer the second option personally.

**Comment by nhyty** [comment]
Also, we need something for translations/adaptations

**Comment by wjdp** [comment]
> Also, we need something for translations/adaptations

#83  :smirk:

**Comment by wjdp** [comment]
## Adaption to 2

Don't use the playwright attribute at all, a lot cleaner

```yaml
---
title: Little Red
devised: cast and crew
```

Outputs 'Devised by cast and crew'

```yaml
---
title: Little Red
devised: true
```

```yaml
---
title: Little Red
devised: yes
```

Outputs 'Devised'
