### ISSUE TITLE
[/collect/show/] Around the Bend in 60 Minutes 

### ISSUE THREAD

**Issue by ntbot** [newtheatre/history-project#411]
End user submitted issue from page: [/collect/show/](http://alpha.history.newtheatre.org.uk/collect/show/)
---

# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | Around the Bend in 60 Minutes 
Playwright | 
Date Start |  /  / 
Date End |  /  / 
Type | NTG's late night review at the Edinburgh Fringe.
Venue | Cephas Cellar

## Cast

Crispin Harris, Peter Holdway plus 2 others. 

## Crew

Stage Manager Patrick Grice
ASM/Pianist Alison Lumb
Bass Peter Sells

## Anything Else

This revue was a sell out at the Cephas Cellar and we opened in a second venue in Cowgate to meet the demand for tickets.

## Submitter

Field | Data
----- | ----
Name | Alison Lumb
Graduated | 1979

## Attempted File Generation

```
---
title: Around the Bend in 60 Minutes 
playwright: 
season: ??? (NTG's late night review at the Edinburgh Fringe.)
season_sort: ??
period: ??
venue:
  - Cephas Cellar
date_start: --
date_end: --

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from Alison Lumb (1979)
published: true
---


```

**
