### ISSUE TITLE
Enable use of SmugMug assets for show assets

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#515]
As we grow our show assets the repo grows with. SmugMug is a tad easier on editors. Looking to migrate to that fully for binary assets.

Something like:

```yaml
assets:
  - type: poster
    smugmug: ABC123
  - type: flyer
    smugmug: ABC124
  - type: programme
    filename: the_pillowman_programme.pdf
    title: Programme
```

PDFs don't live on SmugMug so stay as they are.

We won't be adding SCANFEST assets to repo, they shall wait for this feature.
