### ISSUE TITLE
'Fun Facts' list on show (and possibly people)

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#636]
Bullet pointed list of fun facts on show listing of interesting/unusual points about a performance.

- *The lake flooded the theatre and was swapped out for a smoke machine.*
- *One of the few uses of the old followspot donated by TEC.*
- *Puppets*

Presented around the synopsis area on show pages and with a prominent button to 'send in your own' this could be the first step in getting alumni to contribute. 

If we recorded who sent in the fact their name could show alongside the quote with a link to their person record. I'm unsure about this as it could discourage people from sending in facts.

##### Draft data structure:

```yaml
facts:
  - name: Fred Bloggs
    submitted: 2016-01-01
    fact: Every character in this play was portrayed by a perfectly 
          circular Victoria Sponge.
```
