### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by ntbot** [newtheatre/history-project#642]
End user submitted issue from page: [/collect/show/](https://history.newtheatre.org.uk/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | Test
Playwright | 1234
Date Start | 01 / 01 / 01
Date End |  /  / 
Type | Main
Venue | The Moon

## Submitter

Field | Data
----- | ----
Name | wjdp
Graduated | 1900

## Attempted File Generation

```
---
title: Test
playwright: 1234
season: ??? (Main)
season_sort: ??
period: ??
venue:
  - The Moon
date_start: 01-01-01
date_end: --

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from wjdp (1900)
published: true
---


```
**
