### ISSUE TITLE
The Dinner Game 

### ISSUE THREAD

**Issue by ntbot** [newtheatre/history-project#653]
End user submitted issue from page: [/collect/show/](https://history.newtheatre.org.uk/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | The Dinner Game 
Playwright | Francis Weber
Date Start | 21 / 04 / 2009
Date End | 28 / 04 / 2009
Type | Comedy 
Venue | New Theatre

## Cast

Cem Aytacli 

## Crew

Directed by Paul Cadiou & Nick Rowell 

## Submitter

Field | Data
----- | ----
Name | Nick Rowell
Graduated | 2011

## Attempted File Generation

```
---
title: The Dinner Game 
playwright: Francis Weber
season: ??? (Comedy )
season_sort: ??
period: ??
venue:
  - New Theatre
date_start: 2009-04-21
date_end: 2009-04-28

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from Nick Rowell (2011)
published: true
---


```
**
