### ISSUE TITLE
Add reviews to shows

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#70]
Mission statement includes collecting show reviews.
- What information do we want to collect?
- How should that be marked up

**Comment by wjdp** [comment]
```
reviews:
  - publication: IMPACT
  - stars: 4
  - quote: It was bloody marvellous
```

Other fields:

- Link: if website link available perhaps include. This isn't a great idea as the blogs we're mentioned in may go offline in the future. We could use the Wayback Machine for this?
- Full article text/scan, not a good idea to include in the show file **but** we could make a new collection `_reviews` and link to the copy of the review we have.

**Comment by wjdp** [comment]
Food for thought: If a show gets awful reviews, do we include them?

**Comment by samozzy** [comment]
Can make this happen for this season's shows if you would like. Can also provide example of a _review/show.md if you would like.
*However*: File structure is important. Multiple shows with the same name, and shows with multiple reviews. How would this work?
`_reviews/16_17/closer/impact.md` (`_reviews/yy_yy/showname/reviewsource.md`) seems a little clunky but works.
And then in the showfile.md:
```
reviews: 
     - impact: 
         stars: 4 
         quote: text 
     - kevcastle: 
          stars 3 
          quote: text 
```

Will it then do a clever thing and look for the review.md to output [stars] [text] [our article link]
And then within our article, have [original article external link]?

**Comment by wjdp** [comment]
Righthy ho, looking back at this now it seems that copying in review text is a bit much. We've got the [link list](https://history.newtheatre.org.uk/docs/link-list/) format that has some fields defined for reviews (quote and link) and a strategy to deal with external resources (using archive.is, information in previous link).

While adding a `reviews` attribute to a show now wouldn't do anything we can still start collecting data. A valid addition could be:

```yaml
links:
  - type: review
    href: "http://newssite.com/review-name"
    snapshot: ABC123
    title: Show Name review
    date: 1970-01-01
    stars: 3
    quote: "Was wonderful"
```

We can start adding links as above right away. The show attribute `links` isn't set in stone yet but I've jumped to that rather than `reviews` as there could be other types of link, and is safe for immediate use.
