### ISSUE TITLE
A show

### ISSUE THREAD

**Issue by ntbot** [newtheatre/history-project#761]
End user submitted issue from page: [/collect/show/](https://history.newtheatre.org.uk/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | A show
Playwright | 123
Date Start | 1 / 1 / 1
Date End | 1 / 1 / 1
Type | test
Venue | 1

## Submitter

Field | Data
----- | ----
Name | wjdp
Graduated | 1850

## Attempted File Generation

```
---
title: A show
playwright: 123
season: ??? (test)
season_sort: ??
period: ??
venue:
  - 1
date_start: 1-1-1
date_end: 1-1-1

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from wjdp (1850)
published: true
---


```
**
