### ISSUE TITLE
NSDF awards 2013

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#788]
<img src="https://cloud.githubusercontent.com/assets/1690934/24500716/6d8fd35c-153e-11e7-862f-e880e62727c5.png" align="right" />
Making a note of this here. There's no supported action to put this information on the site yet.

**Comment by samozzy** [comment]
Suggested awards layout: (Is this OTT?)
```
award:
    - title: Best Ensemble
    issued_by: NSDF
    year: 2013
    notes: For 'Jerusalem'
```
Can then extend to:
```
award:
    - title: Best Actor
    issued_by: NNT
    year: 2015
    notes: 'For 'The Tempest'
```
