### ISSUE TITLE
focus-ring styling broken by CSS post-processing

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#791]
As found out when building the focus-ring branch, browsers do not like things they don't understand in CSS selectors. `.focus-ring` and `:focus-ring` are separate in the source, but the post-processor sees they're the same and bundles into a single item. This breaks rendering on some browsers.

Excerpt from built CSS:
```css
.focus-ring,:focus-ring{outline:3px dashed #eee;outline-offset:2px}
```
