### ISSUE TITLE
Stage Names

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#965]
How should we deal with storing stage names????

**Comment by wjdp** [comment]
People change names, usually through marriage or by having the same name as an established person in their chosen field.

```yaml
aliases:
  - type: stage
    name: Joe Bloggs
  - type: married
    name: Joe Froggs
```
